import type { Section } from '@/types/schema';

function createId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

export const emptyTemplate: Section[] = [];

export const caseStudyTemplate: Section[] = [
  {
    id: createId('sec'),
    name: 'Define problem and hypotheses',
    description: 'Establish the problem statement, target audience, and initial hypotheses to guide your research.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What is the problem statement?',
        description: 'Clearly articulate the problem you are solving (e.g., "People with variable pain don\'t remember patterns useful to the doctor; we need ultra-fast logging and readable insights.").',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'checklist',
        title: 'What are your initial hypotheses?',
        description: 'List your key hypotheses (H1, H2, H3, etc.)',
        items: [
          { id: createId('item'), label: 'H1: if logging takes <5 s, adherence increases', done: false },
          { id: createId('item'), label: 'H2: after 7 days, simple insights increase awareness', done: false },
          { id: createId('item'), label: 'H3: weather is useful but sensitive → it must be opt-in', done: false },
        ],
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What is your target audience?',
        description: 'Describe the primary users and their characteristics (e.g., adults 20–60 with episodic/chronic mild-moderate pain).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are your OKRs/KPIs?',
        description: 'Define success criteria and thresholds (e.g., entry time <5 s; completion >90%; insight comprehension ≥80%; SUS ≥75).',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Brief (1 page)', isCompleted: false },
      { id: createId('deliv'), label: 'OKRs/KPIs document', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Research questions and audience',
    description: 'Define your research questions and identify the right participants.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are your key research questions?',
        description: 'List 3–5 priority research questions (e.g., "At what times of day would people log pain/energy?", "Which barriers make them give up?", "Which data are truly useful to the doctor?").',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are your inclusion/exclusion criteria?',
        description: 'Define who should and should not participate.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'number',
        title: 'How many participants do you need?',
        description: 'Target number of participants (e.g., 5–7 users + 1–2 doctors).',
        value: 0,
        min: 1,
        max: 20,
        step: 1,
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: '3–5 priority research questions', isCompleted: false },
      { id: createId('deliv'), label: 'Inclusion/exclusion criteria', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Discovery research plan',
    description: 'Plan your research methods, timeline, and logistics.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What research methods will you use?',
        description: 'Document your methods (e.g., 5–7 semi-structured interviews 20–30\', 1 doctor interview, benchmarking of 3–5 apps).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are the key risks and how will you mitigate them?',
        description: 'Identify potential issues (e.g., social desirability, privacy, health topic sensitivity) and your mitigation strategies.',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Research plan', isCompleted: false },
      { id: createId('deliv'), label: 'Interview guide', isCompleted: false },
      { id: createId('deliv'), label: 'Screener', isCompleted: false },
      { id: createId('deliv'), label: 'Consent form', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Recruitment & logistics',
    description: 'Organize participant recruitment and interview logistics.',
    objectives: [
      {
        id: createId('obj'),
        type: 'number',
        title: 'How many participants have you recruited?',
        description: 'Target: 5–7 users. Document your sample size.',
        value: 0,
        min: 1,
        max: 20,
        step: 1,
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What incentives are you offering?',
        description: 'Document incentive strategy (e.g., symbolic gift card).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What tools will you use?',
        description: 'Document tools for recording and note-taking (e.g., Meet/Zoom, FigJam/Notion).',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Interview schedule', isCompleted: false },
      { id: createId('deliv'), label: 'Recording checklist', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Interviews and synthesis',
    description: 'Conduct research and synthesize findings into actionable insights.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are the key insights from your research?',
        description: 'Summarize 6–10 key insights from your interviews and analysis.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are the Jobs-To-Be-Done?',
        description: 'Identify the core jobs users are trying to accomplish.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are the main barriers and drivers?',
        description: 'List barriers preventing users from achieving their goals and drivers that motivate them.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are the requirements based on research?',
        description: 'Document functional and non-functional requirements derived from insights.',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: '6–10 key insights', isCompleted: false },
      { id: createId('deliv'), label: 'Jobs-To-Be-Done framework', isCompleted: false },
      { id: createId('deliv'), label: 'Barriers/drivers analysis', isCompleted: false },
      { id: createId('deliv'), label: 'Requirements document', isCompleted: false },
      { id: createId('deliv'), label: 'Affinity map (photos)', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Requirements & guiding principles',
    description: 'Define functional requirements and design principles based on your research.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are your design principles?',
        description: 'Document principles (e.g., speed, control, clarity, data respect). Write them in first person ("I log in seconds", "I understand what\'s happening").',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'checklist',
        title: 'What are the MoSCoW requirements?',
        description: 'Categorize requirements as Must have, Should have, Could have, Won\'t have (e.g., entry <5 s; one-handed; offline-friendly; edit within 10 min; weather opt-in and revocable; insights described as associations, not causes).',
        items: [
          { id: createId('item'), label: 'Must have: [Requirement]', done: false },
          { id: createId('item'), label: 'Should have: [Requirement]', done: false },
          { id: createId('item'), label: 'Could have: [Requirement]', done: false },
          { id: createId('item'), label: 'Won\'t have: [Requirement]', done: false },
        ],
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'MoSCoW requirements document', isCompleted: false },
      { id: createId('deliv'), label: 'Acceptance criteria', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'IA and user flows',
    description: 'Design the information architecture and map user journeys.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are the main user flows?',
        description: 'Document key flows (e.g., first-run: weather consent + 3-step tutorial; log; insights: educational empty state if <7 entries; export).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What edge cases need to be considered?',
        description: 'Document edge cases (e.g., no network, permissions denied, time zone/DST).',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Wire-flow with states and fallbacks', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Low-fi wireframes',
    description: 'Create low-fidelity wireframes to establish layout and hierarchy.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What design variants are you testing?',
        description: 'Document variants (e.g., horizontal vs vertical sliders - prepare both for testing). Primary CTA "Save." Optional notes with remaining character count.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What accessibility considerations are included?',
        description: 'Document keyboard navigation, screen reader support, focus management. Ensure CTA within thumb reach for right- and left-handed users.',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Low-fi screens ready for validation', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Content and scales',
    description: 'Define content strategy, scales, and microcopy.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'How are scales defined?',
        description: 'Document scales (e.g., Pain NRS 0–10: 0 = no pain; 10 = worst imaginable. Energy 0–10: 0 = exhausted; 10 = at your peak). Show textual labels (0/10) and a tooltip of the current value.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What is the tone and style of microcopy?',
        description: 'Document microcopy approach (neutral, non-judgmental tone). Example insight: "In the evening, pain is on average +1.8 vs morning (association, not cause)."',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Labels and tooltips', isCompleted: false },
      { id: createId('deliv'), label: 'Error messages', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Mid/hi-fi prototype in Figma',
    description: 'Build an interactive prototype for testing.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What prototyping techniques are you using?',
        description: 'Document techniques (e.g., Auto Layout, Variants, Variables for theme/metrics, interactive prototype with tap/drag/keyboard).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What is included in your design system?',
        description: 'Document components (e.g., sliders, buttons, insight card).',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Navigable prototype', isCompleted: false },
      { id: createId('deliv'), label: 'Mini design system (sliders, buttons, insight card)', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Evaluation R1 (formative test)',
    description: 'Conduct initial usability testing and gather feedback.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are the test tasks?',
        description: 'Document tasks (e.g., A: Log now; B: Edit entry; C: Enable/disable weather; D: Interpret an insight).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What metrics are you tracking?',
        description: 'Document metrics (success, errors, task time, SEQ post-task 1–7 scale, qualitative notes).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are the key findings?',
        description: 'Summarize main usability issues and positive feedback.',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Short report', isCompleted: false },
      { id: createId('deliv'), label: 'Prioritized fix backlog', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Iteration',
    description: 'Refine the design based on testing feedback.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What changes were made based on feedback?',
        description: 'Document key design iterations and rationale. Priorities: reduce entry time; clarify insights; simplify permissions.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What issues were prioritized and why?',
        description: 'Explain prioritization decisions. First remove logging blockers and chart-reading doubts, then polish details.',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Prototype v2', isCompleted: false },
      { id: createId('deliv'), label: 'Changelog', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Visual design and accessibility',
    description: 'Ensure the design meets accessibility standards.',
    objectives: [
      {
        id: createId('obj'),
        type: 'checklist',
        title: 'What WCAG 2.2 AA requirements are met?',
        description: 'Check off implemented accessibility features.',
        items: [
          { id: createId('item'), label: 'Contrast requirements met', done: false },
          { id: createId('item'), label: 'Visible focus indicators', done: false },
          { id: createId('item'), label: 'Coherent tab order', done: false },
          { id: createId('item'), label: 'Keyboard support', done: false },
          { id: createId('item'), label: 'For sliders: alternative numeric input, step = 1, value label', done: false },
          { id: createId('item'), label: 'Charts: not color-only (markers/textures), direct labels', done: false },
        ],
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What accessibility testing was conducted?',
        description: 'Document testing methods and results.',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Accessibility audit', isCompleted: false },
      { id: createId('deliv'), label: 'Accessibility fixes', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Insight view (data-viz)',
    description: 'Design how users will view and understand their data insights.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What charts will be displayed?',
        description: 'Document recommended charts (e.g., time series for pain/energy; simple scatter for weather/time vs pain; bands for time-of-day segments).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'How will insights be communicated?',
        description: 'Document insight sentences with magnitude of difference ("+1.5") and disclaimer ("Observed association, not cause"). Example: "In the evenings (18–22), pain is on average +1.8 vs morning. (Association, not cause.)"',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What are the rules for generating insight sentences?',
        description: 'Document rules (e.g., time-of-day bands: if average pain 18–22 ≥ average 6–10 + 1.5 → "evenings tend to be worse (+X)").',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Layout + rules for sentence generation', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Export for the doctor',
    description: 'Design the export functionality for sharing data with doctors.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What data will be exported?',
        description: 'Document export contents (e.g., 1-page PDF: range, median, variation, top 2 insights; CSV with entries). Note: "subjective data, not diagnostic."',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'How will privacy be maintained?',
        description: 'Document privacy considerations (e.g., anonymous header with initials and date range; no sensitive health data).',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Export mock', isCompleted: false },
      { id: createId('deliv'), label: 'Filled example', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Evaluation R2 (summative test)',
    description: 'Conduct follow-up testing after iterations.',
    objectives: [
      {
        id: createId('obj'),
        type: 'number',
        title: 'How many participants tested in round 2?',
        description: 'Target: 5 new users + 1 doctor.',
        value: 0,
        min: 1,
        max: 20,
        step: 1,
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'number',
        title: 'What was the final SUS score?',
        description: 'Target: ≥75 (good usability).',
        value: 0,
        min: 0,
        max: 100,
        step: 1,
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What was the focus of round 2?',
        description: 'Document focus areas (e.g., insight comprehension, export usefulness). Use SUS and UMUX-Lite.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'Did you meet your success criteria?',
        description: 'Compare results against your OKRs/KPIs (entry completion rate >90%; median time per entry <5s; insight comprehension ≥80%; SUS ≥75).',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Results + comparison with R1', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: createId('sec'),
    name: 'Case study for portfolio',
    description: 'Document your process and outcomes for your portfolio.',
    objectives: [
      {
        id: createId('obj'),
        type: 'text',
        title: 'What is the project overview?',
        description: 'Brief summary: context & role, problem & goals (KPIs).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'How did you conduct research?',
        description: 'Document research methods, sample, key insights.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What was your design process?',
        description: 'Document requirements & principles, IA, wireframes, prototype (include clips/gifs).',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What were the test results?',
        description: 'Document R1 test → Iterations → R2 test with KPIs before/after.',
        value: '',
        isCompleted: false,
      },
      {
        id: createId('obj'),
        type: 'text',
        title: 'What were the key learnings?',
        description: 'Reflect on what you learned throughout the process. Document lessons learned and future improvements.',
        value: '',
        isCompleted: false,
      },
    ],
    deliverables: [
      { id: createId('deliv'), label: 'Portfolio page with images', isCompleted: false },
      { id: createId('deliv'), label: 'Figma link', isCompleted: false },
      { id: createId('deliv'), label: 'Essential artifacts', isCompleted: false },
      { id: createId('deliv'), label: 'Written case study with storytelling and evidence', isCompleted: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
